### ISSUE TITLE
Support volumes through Kitematic

### ISSUE THREAD

**Issue by marcelorodrigo** [phpmentors-jp/docker-images#8]
There's currently no way using Docker with Kitematic to add a volume for a specific directory unless it was defined in the Dockerfile as a VOLUME directive.

The suggestions is expose the app volume through the Dockerfile, and then is possible to change it via Kitematic

**Comment by iteman** [comment]
The `VOLUME` instruction in all phpmentors/* images has been specified either explicitly or implicitly. Please let me know if Kitematic requires the explicit `VOLUME` definition in each Dockerfile to expose the volumes defined in a Docker container. I cannot use Kitematic because I use Ubuntu.

kitematic/kitematic#722 will fix this as well.

**Comment by zedtux** [comment]
@iteman don't you know there's a linux support now ? :) Have a look at this: https://github.com/kitematic/kitematic/wiki/Early-Linux-Support

**Comment by iteman** [comment]
@marcelorodrigo @zedtux Thank you! :smile:
